### ISSUE TITLE
Importing agateexcel prevents exiting with non-zero status

### ISSUE THREAD

**Issue by lcorbasson** [wireservice/agate-excel#31]
Hi,
MWE with agate-excel 0.2.2 (Python 3.6):
`import agateexcel`
`raise Exception()`

When agateexcel isn't imported, the script exits with code 1; if agateexcel is present, it exists with code 0.

**Comment by lcorbasson** [comment]
Closing, found out that it's an issue emerging from openpyxl (imported by agateexcel).

**Comment by lcorbasson** [comment]
For reference, following module imports led to `pandas`, whose the traceback gave:
`Traceback (most recent call last):`
`  File "exittest.py", line 48, in <module>`
`    import pandas._libs.testing`
`  File "/usr/lib/python3.6/site-packages/pandas/__init__.py", line 51, in <module>`
`    import pandas.testing`
`  File "/usr/lib/python3.6/site-packages/pandas/testing.py", line 7, in <module>`
`    from pandas.util.testing import (`
`  File "/usr/lib/python3.6/site-packages/pandas/util/testing.py", line 20, in <module>`
`    from pandas._libs import testing as _testing`
`ImportError: Permission denied`

This was fixed by reinstalling `pandas`.
