### ISSUE TITLE
from_xls() failes when a cell =1 and is formatted as a date

### ISSUE THREAD

**Issue by nacnudus** [wireservice/agate-excel#9]
Problem file: [temp.zip](https://github.com/wireservice/agate-excel/files/511385/temp.zip)

``` python
Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import agate
>>> import agateexcel
>>> agateexcel.patch()
>>> agate.Table.from_xls('temp.xls')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/appl/anaconda/anaconda3/lib/python3.5/site-packages/agateexcel/table_xls.py", line 52, in from_xls
    values = normalize_dates(values, book.datemode)
  File "/appl/anaconda/anaconda3/lib/python3.5/site-packages/agateexcel/table_xls.py", line 102, in normalize_dates
    v_tuple = xlrd.xldate_as_tuple(v, datemode)
  File "/appl/anaconda/anaconda3/lib/python3.5/site-packages/xlrd/xldate.py", line 86, in xldate_as_tuple
    raise XLDateAmbiguous(xldate)
xlrd.xldate.XLDateAmbiguous: 1.0
>>>
```

Possibly related: https://github.com/wireservice/csvkit/issues/607

**Comment by jpmckinney** [comment]
Directly related https://github.com/wireservice/csvkit/issues/577
